# Generated by Django 5.0.4 on 2024-04-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_permisoproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisoproducto',
            name='puede_agregar',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='permisoproducto',
            name='puede_cambiar',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='permisoproducto',
            name='puede_eliminar',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='permisoproducto',
            name='puede_ver',
            field=models.BooleanField(default=True),
        ),
    ]
