# Generated by Django 5.0.4 on 2024-04-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0004_alter_permisoproducto_puede_agregar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisoproducto',
            name='puede_agregar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permisoproducto',
            name='puede_cambiar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permisoproducto',
            name='puede_eliminar',
            field=models.BooleanField(default=False),
        ),
    ]
